# DigitalOcean installer.71m.us

name: Scoold
image: ubuntu-18-10-x64
min_size: 1gb
config:
  users:
    - name: ubuntu
      groups: sudo
      shell: /bin/bash
  packages:
    - wget
    - openjdk-11-jre
  runcmd:
    - "cd /home/ubuntu/ && wget https://raw.githubusercontent.com/Erudika/scoold/master/installer.sh && bash installer.sh"
